### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by vladrip** [vladrip/ifchat-android#1]
- [ ] Rewrite UI in Jetpack Compose
- [x] Use Firebase Auth UI
- [x] Create some sort of queue for uncompleted api requests, such as message sending or deletion, so it can be completed later when client will be connected to the internet.
- [x] Maybe better check on client if he wants to receive notification (chatMuted)? Instead of storing it on server.
- [x] Check if user is online maybe with: https://firebase.google.com/docs/firestore/solutions/presence
